### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AliRichter** [mkjeff/secs4net#11]
hi, I'm very interested in your project. when I'm right is this the site from host or from both sides?

my equipment simulation send auto S1F13 - now your sample must send S1F14 - i'm not shoure how?

can you help me?

best regards

**Comment by mkjeff** [comment]
Actually, this project was initiated to meet CIM host control system. I suppose it has the ability, according to the API interface. Maybe you can try first and welcome any feedback.

**Comment by zhuwei3359** [comment]
@mkjeff  do you mean that this project is like an equipment, not a host?

**Comment by AliRichter** [comment]
hi, thanks for your awnser.
I need to provide the values of my control via the SECSinterface of a monitoring program. Is this possible with your project?

**Comment by AliRichter** [comment]
hi, I have tried it. after some change now I can communicate. Is everything in the project necessary? How can I add some specific SML?
