### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by KarloX2** [mkjeff/secs4net#15]
Hello!
I find no license information about this project. Can you please add it? Is it licensed under MIT terms?

Thanks

**Comment by zakk2chiu** [comment]
Hi, mkjeff,

Your project really help, and I also want to know the license information
Thanks your share again.

**Comment by ssathasivan** [comment]
Can we use this project in other applications

**Comment by mkjeff** [comment]
> Hello!
> I find no license information about this project. Can you please add it? Is it licensed under MIT terms?
> 
> Thanks

Yes, it is MIT licensed.
