### ISSUE TITLE
Try To start EAP Host 

### ISSUE THREAD

**Issue by lhf552004** [mkjeff/secs4net#17]
Hi, I'm trying to start the EAP Host. Then there is an error dialogue. It says "相關組態檔找不到"
![image](https://user-images.githubusercontent.com/10030850/30093074-8e77e3b8-92f5-11e7-91ec-932ccd529679.png)
The problem is I can't debug into the code. It's strange. why.

**Comment by dzhydaniel** [comment]
did you get any progress on this bug?

**Comment by mkjeff** [comment]
The EAP application entry point is driver project(e.q. PEU01/MWN01). The project 'Debug' setting need to point 'Start External Program' to the path of EAP.exe

**Comment by dzhydaniel** [comment]
![image](https://user-images.githubusercontent.com/44791363/57824502-d4944a80-77cd-11e9-934d-e1b720b3d72c.png)
guys plese help how to deal with this error

**Comment by dzhydaniel** [comment]
did you solved your problem?

**Comment by dzhydaniel** [comment]
@lhf552004 did you got any progress on this ?

**Comment by andihuang2019** [comment]
When running eaphost, the following error is reported。
===================================
---------------------------
程式發生嚴重錯誤而終止
---------------------------
System.Runtime.Remoting.RemotingException: TCP 信道协议冲突: 应为报头。



Server stack trace: 

   在 System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadAndMatchPreamble()

   在 System.Runtime.Remoting.Channels.Tcp.TcpSocketHandler.ReadVersionAndOperation(UInt16& operation)

   在 System.Runtime.Remoting.Channels.Tcp.TcpClientSocketHandler.ReadHeaders()

   在 System.Runtime.Remoting.Channels.Tcp.TcpClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)

   在 System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)



Exception rethrown at [0]: 

   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)

   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)

   在 Cim.Services.IServiceManager`1.Publish(String serviceId, String serviceUrl)

   在 Cim.Eap.Program.PublishZService() 位置 D:\PROJECT\CSP Line\SourceCode\SECS\secs4net-master\secs4net\Core\EAPHost\Program.cs:行号 97

   在 Cim.Eap.Program.Main() 位置 D:\PROJECT\CSP Line\SourceCode\SECS\secs4net-master\secs4net\Core\EAPHost\Program.cs:行号 86
===================================
