### ISSUE TITLE
Unable to install Nuget Package on VS 2017

### ISSUE THREAD

**Issue by weeening** [mkjeff/secs4net#19]
Hi, @mkjeff  I tried to install the Nuget Package but it keep failing to install. 

The error message: Could not install package 'Secs4Net 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I'm currently using Visual Studio 2017 on Windows 10 and the project target framework is .NET 4.6.1. 
Would be great if you could provide some suggestions on this, thank you!

**Comment by mkjeff** [comment]
because the project was targeting to 4.6.2
![image](https://user-images.githubusercontent.com/15941979/34926647-cd5d61ae-f9eb-11e7-9d37-07f85d19d58e.png)

**Comment by weeening** [comment]
Hello, I changed the target framework and it worked! Thank you so much :)
