### ISSUE TITLE
Receiving large reply message

### ISSUE THREAD

**Issue by kelvinMyh** [mkjeff/secs4net#24]
hi Jeff
I was running the EAPhost, after sending an S1F3 requesting all SVs, the eq replied with over 400 items, and after receiving the first buffer (0x4000 bytes), the program stopped responding to any action, and soon ended itself. I tried to use some try catches, but none break point in the exception section was spotted.
appreciation for any reply.

**Comment by a-v-kalabuhov** [comment]
The list data items in SecsMessage are limited up to 255 elements. It may be a reason why the program did crash.

**Comment by BinaryAssault** [comment]
I ran into this issue (or at least something similar) and was able to get a workaround. I was receiving a reply message that was very big (list of >55000). Problem was, the ReceiveBufferSize in the SecsGem class was too small. I am not a creator of the SW I am working on, so I cannot give code snippets. 

But if you change the ReceiveBufferSize for the socket to accommodate your data on instantiation, it should continue to work.

**Comment by a-v-kalabuhov** [comment]
> it should continue to work.

Thank you very much!

**Comment by dzhydaniel** [comment]
kelvin，can you share how to start up EAP Host

**Comment by a-v-kalabuhov** [comment]
BinaryAssault, I meant there is a hardcoded limitation in secs4net.
It's just not possible to add to a message a list with more than 255 elements.
But array item length isn't limited.

**Comment by TiltonJH** [comment]
Well the issue is in the type, where the 2 last Bits determine the size of the length value. Secs supports up to 3 Byte for length value. Secs4Net only ever uses 1 Byte.

The issue should mostly be within the Item class.

If no one else will fix this. I will. But not within the next month. I currently don't got the time.

**Comment by TiltonJH** [comment]
I have created a pull request (#37), which fixes this issue.

Or have a look here: https://github.com/TiltonJH/secs4net

**Comment by a-v-kalabuhov** [comment]
> I have created a pull request (#37), which fixes this issue.
> 
> Or have a look here: https://github.com/TiltonJH/secs4net

Thanks!

**Comment by mkjeff** [comment]
Thanks for @TiltonJH contribution. I'm happy to see the fork.

btw, welcome to taste [v2](https://github.com/mkjeff/secs4net/tree/v2)
