### ISSUE TITLE
SECS-I (E4) support

### ISSUE THREAD

**Issue by newbie456838** [mkjeff/secs4net#25]
Hi,

Is that possible to add in the connection mode for serial port using SESC-I standard?

**Comment by mkjeff** [comment]
I don't have a spec. but I have added an abstraction layer for physical connection in [v2](https://github.com/mkjeff/secs4net/blob/v2/secs4net/Core/Secs4Net/IHsmsConnection.cs).

not sure if extensibility quire enough, you might take a look.
