### ISSUE TITLE
这什么原因直接编译的 我改成4.5 framework

### ISSUE THREAD

**Issue by Messilimeng** [mkjeff/secs4net#3]
![image](https://cloud.githubusercontent.com/assets/12272166/20000549/ec925a70-a2b2-11e6-874c-2ee4557032a6.png)

**Comment by mkjeff** [comment]
because Array.Empty<T>() method lacked in framework 4.5

**Comment by Messilimeng** [comment]
@mkjeff  我用过怎么处理 升级4.6.2 framework

**Comment by Messilimeng** [comment]
@mkjeff  我把版本换成4.6.1 目前可以很好的运行

**Comment by Messilimeng** [comment]
@mkjeff  请问什么时候出支持.net formwork core 版本的

**Comment by mkjeff** [comment]
@Messilimeng 目前的 SecsCore專案要移植到.net core應該不是什麼問題(外部相依性最小), 但因為開發工具支援度太差了, 整個專案要全移植不好處理, 而且微軟也打算在 .net core v2 讓專案黨無痛升級成新的XML格式(project.json不曉得會不會活著). 所以目前不打算移植.
