### ISSUE TITLE
I can't debug into Header.EncodeTo

### ISSUE THREAD

**Issue by jesse-gao** [mkjeff/secs4net#32]
**Describe the bug**
使用SecsDevice调试时，可以成功连接EQP，但是连接之后一直无法发送Selected消息。

**To Reproduce**
1. 启动SecsDevice项目；
2. 输入合适的IP和Port；
3. 点击Enable按钮；
4. See Error

**Expected behavior**
HOST发送Selected消息并且成功建立连接

**Screenshots**
![2019-06-25_102224](https://user-images.githubusercontent.com/8031903/60064540-506da500-9733-11e9-9051-fd010790b6a9.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Browser Chrom/Edge
 - Version 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mkjeff** [comment]
![image](https://user-images.githubusercontent.com/15941979/60101369-39a86c00-978e-11e9-86da-55f709657a0e.png)
這是某些舊式 nuget package 的問題, 間接相依的 nuget 組件不會被拷貝至輸出目錄, 

This is due to the old nuget package issue that msbuild would not copy the dependencies package which not reference by project directly. 

I have committed a new version. You can try again.

Thanks for your participation.

**Comment by jesse-gao** [comment]
Thank you very much!!!

I manually copied the nuget dll file to the output directory and it worked well.
[cid:image002.png@01D52E6A.C01DD7D0]
[cid:image006.png@01D52E6A.C01DD7D0]

I still don’t know how to automatically copy the nuget dll file to output directory~~

Send from 高红杰


________________________________
发件人: Hsinchang <notifications@github.com>
发送时间: Tuesday, June 25, 2019 9:47:17 PM
收件人: mkjeff/secs4net
抄送: jesse-gao; Author
主题: Re: [mkjeff/secs4net] I can't debug into Header.EncodeTo (#32)


[image]<https://user-images.githubusercontent.com/15941979/60101369-39a86c00-978e-11e9-86da-55f709657a0e.png>
@是某些f式 nuget package 的}, g接相依的 nuget M件不豢截至出目,

This is due to the old nuget package issue that msbuild would not copy the dependencies package which not reference by project directly.

I have committed a new version. You can try again.

Thanks for your participation.

―
