### ISSUE TITLE
memory leak??

### ISSUE THREAD

**Issue by tazu08408** [mkjeff/secs4net#33]
Hi,

Is there anyone facing the memory grow issues running over 24/7 ?
From my observation, the memory allocations of my application
will keep on increasing upon sending the new secs message.
Is it normal ?

**Comment by TiltonJH** [comment]
No it is not normal. the reason are the not reused or disposed SocketAsyncEventArgs. I fixed it. I am preparing to a pull request.

**Comment by tazu08408** [comment]
Thank you!
I want to use the improved software. 
I am waiting to be merged.

**Comment by dzhydaniel** [comment]
@tazu08408 do you have any progress of this project ? can you run EAP Host?

**Comment by tazu08408** [comment]
@dzhydaniel 
No, there is no progress on this project.
A memory leak occurred in the development of an application using this library.
Check the operation on the EAP host.
Are there any results that do not cause memory leaks?

**Comment by dzhydaniel** [comment]
@tazu08408 did you can run MWN01 or PEU01？ i can't, this has bugging me for a very long time.

**Comment by dzhydaniel** [comment]
@tazu08408 @TiltonJH  hi guys do you have the intreast of start a group on we chat

**Comment by tazu08408** [comment]
@dzhydaniel 
I would like to actively discuss SECS communications.
The platform to discuss may be any SNS.

**Comment by tazu08408** [comment]
@dzhydaniel 
MWN01 and PEU01 are not used.
It uses only the SECS communication function and uses the original wrapper library based on SECS4NET.
We are developing communication software for semiconductor devices.

**Comment by dzhydaniel** [comment]
> @dzhydaniel
> I would like to actively discuss SECS communications.
> The platform to discuss may be any SNS.

seems only two of us are active offtenly.

**Comment by tazu08408** [comment]
Do you discuss here?
There is a possibility that others will cooperate.

**Comment by dzhydaniel** [comment]
let's keep post Q&A here.

**Comment by tazu08408** [comment]
What are the challenges with SECS4NET?
I have problems with memory leaks and I have not been able to identify the cause either in SECS4NET or my own library.

**Comment by dzhydaniel** [comment]
I have not run into memory leak problem yet, right now i am trying to set auto reply mechanism, and try to figure out how to define message,how to update item value in one message.

**Comment by dzhydaniel** [comment]
I just find out it can be this way to get one secsmessage . 
string key = "S" + e.Message.S.ToString() + "F" + (e.Message.F+1).ToString();
SelectedSecsCommand = SecsRuntime.FindCommand(key);
SelectedSecsCommand.Message.ToSecsMessage()

**Comment by dzhydaniel** [comment]
How to set or  update secs item value in common.sml
CRA:'S1F66' 
    <L[2]
        <B[1] 0>
        <L[2]
            <A[1] ''>
            <A[1] ''>
        >
    >

**Comment by dzhydaniel** [comment]
> How to set or  update secs item value in common.sml
> CRA:'S1F66'
> <L[2]
> <B[1] 0>
> <L[2]
> <A[1] ''>
> <A[1] ''>
> >
> >
@westjeffho

**Comment by dzhydaniel** [comment]
> How to set or  update secs item value in common.sml
> CRA:'S1F66'
> <L[2]
> <B[1] 0>
> <L[2]
> <A[1] ''>
> <A[1] ''>
> 
> 
> 
@westjeffho @tazu08408

**Comment by dzhydaniel** [comment]
![image](https://user-images.githubusercontent.com/44791363/61843220-7ec6d780-aecd-11e9-8cdf-ad58b12a91f5.png)

how do you build secs message like s1f12?
@tazu08408 @westjeffho

**Comment by TiltonJH** [comment]
Hi,

in order for the pull request, I need to solve a Git problem. I cloned this repository to our on site TFS. I am still new to Git and can not figure out how to create the pull request from our master on the on site TFS to this repository on GitHub. Can someone help me or give me a push in the direction of the solution?

**Comment by Metetron** [comment]
Hi,

I am also no git master, but i think one of the easiest solutions would be to clone the repository from the tfs to your local machine and change the remote to the github address and then create the pull request.

The command for doing this should look like this:
`git remote set-url origin https://github.com/USERNAME/REPOSITORY.git`

**Comment by TiltonJH** [comment]
I have created the promised pull request to fix the memory leak (and other issues) #35

**Comment by dzhydaniel** [comment]
@TiltonJH how to contact you besides this frum

**Comment by TiltonJH** [comment]
@dzhydaniel Contact me? To what end?

**Comment by dzhydaniel** [comment]
my company need secs/gem solution, it appears you have alot know-how and technical skills, i think may be my company and you can work together .

**Comment by dzhydaniel** [comment]
@TiltonJH my company need secs/gem solution, it appears you have alot know-how and technical skills, i think may be my company and you can work together .

**Comment by TiltonJH** [comment]
@dzhydaniel thx, but I am germany based and currently working for a company which sells a product which uses secs4net. Maybe this could be your secs/gem solution. Have a look at [www.inqu.de.](www.inqu.de) especially for our InQu.MDA.

**Comment by Gavenvincent** [comment]
The same thing happened to me,There's going to be a memory leak every time when click the send button.
Steps to reproduce the behavior:
1.Start two instances
2. Connection successful
3. passive form send messages to the active form,and successfully
4. Then,there's going to be a memory leak every time when click the send button.
![83803058-7559ee80-a6de-11ea-9321-6cb313fa299a](https://user-images.githubusercontent.com/49948282/83827647-680a2780-a711-11ea-9647-fd43ff791143.jpg)

**Comment by TiltonJH** [comment]
@Gavenvincent You are welcome to try [https://github.com/TiltonJH/secs4net](https://github.com/TiltonJH/secs4net). I fixed the leak there. I also created a pull request, but mkjeff does not seam to be interested in it.

**Comment by Gavenvincent** [comment]
@TiltonJH  That's really awesome.I will try and I would like to know where exactly is mkJeff's memory leak ,then do some detailed memory analyses.

**Comment by TiltonJH** [comment]
The reason are the not reused or disposed SocketAsyncEventArgs as described here: [SocketAsyncEventArgs Class#Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketasynceventargs?view=netcore-3.1#remarks)

I also fixed an issue where messages went missing, because only the first message were extracted from the buffer.

**Comment by Gavenvincent** [comment]
@TiltonJH Thank you very much ! I'll start with that.

**Comment by 0daycrack** [comment]
@TiltonJH I hava tried your https://github.com/TiltonJH/secs4net ,but there's still going to be a memory leak every time when click the send button.How can i fix it?
Thank you~

**Comment by TiltonJH** [comment]
@0daycrack Any more information on that? How do you arrive at this conclusion?
I could not find a leak in all my extensive tests.

**Comment by 0daycrack** [comment]
@TiltonJH Hi, I use a timer to cycle send messages,
The following are my codes:
```
①Button Click
        private  void btnSendPrimary_Click(object sender, EventArgs e)
        {
            timer1.Interval = 10;
            timer1.Enabled = true;
        }
```
```
②Timer Event
        private async void timer1_Tick(object sender, EventArgs e)
        {
            if (_secsGem.State != ConnectionState.Selected)
                return;
            if (string.IsNullOrWhiteSpace(txtSendPrimary.Text))
                return;
            try
            {
                var reply = await _secsGem.SendAsync(txtSendPrimary.Text.ToSecsMessage());
                txtRecvSecondary.Text = reply.ToSml();
            }
            catch (SecsException ex)
            {
                txtRecvSecondary.Text = ex.Message;
            }
        }
```
The following are my steps:
1.Start two instances
2. Connection successful
3. passive form send messages to the active form,and successfully
4. Then,there's going to be a memory leak
![Meixin20200616143303](https://user-images.githubusercontent.com/51659535/84739646-9542b980-afde-11ea-961c-c7cd581f382f.png)

**Comment by TiltonJH** [comment]
@0daycrack Hi, So you lock at the memory allocation and it steadily grows?

You could use Visual Studio Diagnostic Tools to analyze your memory with memory snapshots (while debugging) and determine what kind of object or objects remain. Once that is done and it is actually a object from within secs4net. I can take a look where that object is used and where it is kept and for what purpose. And then fix the issue.

It could also be possible that it is not sec4net, but your UI that keeps things referenced and thereby keep the GC from collecting it.

**Comment by 0daycrack** [comment]
@TiltonJH HI,Thanks~
This problem is caused by my UI!

**Comment by YandaLiang** [comment]
@TiltonJH  Hi,I have tried your [](https://github.com/TiltonJH/secs4net ), It has solved the memory leak problem, but I have found another problem:
The reconnection problem occurs After frequently disconnecting the device when the program is running in Active mode。

**Comment by YandaLiang** [comment]
@TiltonJH  Hi,I have tried your [](https://github.com/TiltonJH/secs4net ), It has solved the memory leak problem, but I have found another problem:
The reconnection problem occurs After frequently disconnecting the device when the program is running in Active mode。

**Comment by YandaLiang** [comment]
@TiltonJH  Hi,I have tried your [](https://github.com/TiltonJH/secs4net ), It has solved the memory leak problem, but I have found another problem:
The reconnection problem occurs After frequently disconnecting the device when the program is running in Active mode。

**Comment by YandaLiang** [comment]
@TiltonJH  Hi,I have tried your [](https://github.com/TiltonJH/secs4net ), It has solved the memory leak problem, but I have found another problem:
The reconnection problem occurs After frequently disconnecting the device when the program is running in Active mode。

**Comment by YandaLiang** [comment]
@TiltonJH  Hi,I have tried your [https://github.com/TiltonJH/secs4net](https://github.com/TiltonJH/secs4net ), It has solved the memory leak problem, but I have found another problem:
The reconnection problem occurs After frequently disconnecting the device when the program is running in Active mode。

**Comment by teonsen** [comment]
@TiltonJH is awesome! but I faced the same issue on reconnecting at active mode just like @YandaLiang said.
It seems to be the async task is not canceled when Retry. This ends up "Connection Exhaust" easily.
I upload the fixed version here. (it's only a sample. never tested.)
https://github.com/teonsen/secs4net/tree/dev

hope this helps.

**Comment by TiltonJH** [comment]
@teonsen Great! If someone tests this and I'll get a pull request I will merge this.

@YandaLiang BTW: Shouldn't this be filed under a different issue?

**Comment by freesiafreesia** [comment]
> I also fixed an issue where messages went missing, because only the first message was read from the buffer.

@TiltonJH Hi, Could you tell me which commit did you fix this issue in your pull request #35?

**Comment by Gavenvincent** [comment]
@TiltonJH A new bug was recently discovered using your project,it is:
1.Start two instances
2. Connection successful
3. But it quickly becomes buggy
![Uploading HSMS BUG 20210602.JPG…]()

**Comment by Gavenvincent** [comment]
@TiltonJH 
![HSMS BUG 20210602](https://user-images.githubusercontent.com/49948282/120480893-1eb2ed80-c3e2-11eb-8cd6-e281e5a2c5e5.JPG)
 A new bug was recently discovered using your project,it is:
1.Start two instances
2. Connection successful
3. But it quickly becomes buggy

**Comment by TiltonJH** [comment]
Well, yes I have noticed that too. However, I currently don't have the time to investigate or fix it.

If someone would provide a fix (pull request) for it, I would take a look and integrate it.

**Comment by mkjeff** [comment]
the memory usage is a big target on the v2 roadmap. welcome to test [v2](https://github.com/mkjeff/secs4net/tree/v2)
