### ISSUE TITLE
Response not sent in V2.0.0-RC01

### ISSUE THREAD

**Issue by Metetron** [mkjeff/secs4net#34]
**Describe the bug**
I mainly develop with .Net Core and so I tried to use the 2.0.0-RC01 version on nuget.
Our equipments send an S1F13- Request to the Host after the connection is established.
The Host should then reply with an S1F14 acknowledge.

After implementing the host- side software, we encountered the following behaviour:

The Host receives the PrimaryMessage, but the reply does not reach the equipment.
I then tested the same scenario with the 1.0.0 version from nuget. 
This version worked as expected.

I programmed a little sample project to illustrate the behaviour.

**To Reproduce**

with version 1.0.0:
Start the project V1_Passive and then V1_Active after that. In the console you see that the connection is established, the equipment sends the S1F13- Request and the host responds accordingly.

with version 2.0.0-RC01:
Start the project V2_Passive and then V2_Active after that. In the console you see, that the connection is established and the equipment sends the request, but the hosts response does not reach the equipment. Finally the T3- timer runs out after 3 retries.

**Expected behavior**
The response from the host should reach the equipment like in version 1.0.0.

**Desktop (please complete the following information):**
 - OS: Windows 10 1709
- Visual Studio 2019 Version 16.1.6
- Net Core SDK 2.2.500
- Net Framework 4.7.2

**Additional context**
Here is the test project to help you: 
[Secs4NetTest.zip](https://github.com/mkjeff/secs4net/files/3376252/Secs4NetTest.zip)

Is v2 supposed to be used? Or should I use v1 for now, until v2 is officially released?
If so, is there a way for you to make v1 compatible with .Net Standard, so that we can use it in .Net Core?

**Comment by OrangeUtan84** [comment]
I can also reproduce this behavior. When I'm using active host and passive equipment and the host sends S1F13 and the equipment replies with S1F14 + MDLN + SOFTREV. But the reply doesn't reach the host and the host waits until T3 timeout.

@Metetron You closed the issue. Could you find out anything to fix this issue? 

Kind regards

**Comment by Metetron** [comment]
Yes, I found the issue. You should not directly access the connection in the ConnectionChanged handler. I don`t know if this is a problem in the library or a difference in behaviour in .Net Framework and .Net Core.

This is the code I wrote to send the S1F13 command in the equipment:
```csharp
connection.ConnectionChanged += async (sender, state) =>
{
    Console.WriteLine(state);

    if (state == ConnectionState.Selected)
    {
        var reply = await connection.SendAsync(establishConnectionRequest);
        Console.Write(reply);
    }
};
```

If you want to send a message on state change, you have to write the code like this:
```csharp
connection.ConnectionChanged += async (sender, state) =>
{
    Console.WriteLine(state);

    if (state == ConnectionState.Selected)
    {
        await  Task.Run(() => await connection.SendAsync(establishConnectionRequest));
    }
};
```

I have built a host, that is used in production with the RC01 version and it is working fine.

**Comment by OrangeUtan84** [comment]
@Metetron Thanks a lot!! After modifying the code to send S1F13 in a new task it worked like charm.
