### ISSUE TITLE
In some cases, the Secs server cannot connect

### ISSUE THREAD

**Issue by semonpic** [mkjeff/secs4net#36]
**Describe the bug**
In some cases, the Secs server cannot connect。Passive/Active SecsDevice can not connect each other’.

**To Reproduce**
1. Start 2 Active SecsDevice  and 1 Passive SecsDevice,  then enable them.
2. On the Passive SecsDevice ,Alternate click Enable button  and Disable button at 5 seconds intervals。
3. See,3 SecsDevice will Enter Hte "Connectting" State. Passive SecsDevice will never work  properly
。
**Expected behavior**
This may be cause by multithread. In file SecsGem.cs ,_startImpl  may be Start many times。
Each communication error occurr will trigger function "CommunicationStateChanging(in ConnectionState newState)",then _startImpl  will be started. If multiple errors occur simultaneously，multiple  _startImpl  threads will start。But we only have one woke socket.
socket will be open and close in more than one  _startImpl  thread.
How do we ensure that there is only one  _startImpl  thread running when multiple error occurs

**Screenshots**

![screen](https://user-images.githubusercontent.com/9736737/63905636-6e16fd80-ca47-11e9-9093-c1f7bc853ec9.jpg)

**Desktop (please complete the following information):**
 - OS: [Win 7]

**Additional context**

**Comment by nevernet** [comment]
where is your host server? 
or simulator?

**Comment by zhuxuan1997** [comment]
> where is your host server? or simulator?

in this  source code file , the DeviceWorkerService project supply the host server.
you can run  DeviceWorkerService project and SecsDevice two project simultaneously in VS.

**Comment by jiayueshe** [comment]
我也遇到这种情况，连接不上
