### ISSUE TITLE
Decode Hex to Ascii

### ISSUE THREAD

**Issue by Swiftpaws** [mkjeff/secs4net#40]
A way to decode hex into their SML Ascii formats would be nice.

Example:
From
00 00 06 06 00 00 00 00 6e 2a 21 01 00 
To
S6F6 
<B[1] 00>

**Comment by mkjeff** [comment]
Welcome to put your eyes on [v2]( https://github.com/mkjeff/secs4net/tree/v2).

[this](https://github.com/mkjeff/secs4net/blob/v2/secs4net/Core/Secs4Net/Item.Decode.cs#L61)is a similar method in v2, but internal.
