### ISSUE TITLE
Function number error in json

### ISSUE THREAD

**Issue by n696395** [mkjeff/secs4net#51]
Function number error in JsonExtension and same as in v2 JsonWriter.

```cs
await jwtr.WritePropertyNameAsync(nameof(msg.F));
await jwtr.WriteValueAsync(msg.S);
```

v2
```cs
jwtr.WriteNumber(nameof(msg.F), msg.S);
```

**Comment by mkjeff** [comment]
v2 fixed https://github.com/mkjeff/secs4net/tree/ddb3f1993fc427fbfcb1dd44c65fea59948dc3f8
