### ISSUE TITLE
SecomSimulator can't connect my application with  secs4net

### ISSUE THREAD

**Issue by BruceQiu1996** [mkjeff/secs4net#56]
Hi ,i used a SecomSimulator tool to connect my applicaiton, but can't connect .under is details ,can you give me some suggestions or helps.

![image](https://user-images.githubusercontent.com/28331315/132653400-2a2de7c5-e0f1-49be-a0d2-1c60a9df7806.png)
![image](https://user-images.githubusercontent.com/28331315/132653469-552f5e83-5857-432a-88e8-4343132a65e2.png)
![image](https://user-images.githubusercontent.com/28331315/132653597-d8cf7f16-6e35-416c-b44d-08e102ed6932.png)
![image](https://user-images.githubusercontent.com/28331315/132653921-19fdb871-e82d-408c-b770-72aa479eceb4.png)

**Comment by mkjeff** [comment]
use `"IsActive": false` settings at secs4net configuration if the SecomSimulator's "Connection Mode" is `Active`
