### ISSUE TITLE
Sometime can't reply message

### ISSUE THREAD

**Issue by tondangerza** [mkjeff/secs4net#59]
Hi,
I found some issue when I send sec message from host to equipment(secs4net) as S1F1 
but sometime equipment not reply S1F2, How do I do that?

![image](https://user-images.githubusercontent.com/51964193/135365563-f664c3ae-9e22-46f7-a7d1-6a9b9aef4a2a.png)

**Comment by mkjeff** [comment]
Please provider complete source repo. That would be helpful for the people wanna to help.

**Comment by tondangerza** [comment]
Thank you it work for me ^ ^
