### ISSUE TITLE
Request/Suggestion

### ISSUE THREAD

**Issue by SEPTEMBER998767** [mkjeff/secs4net#6]
On 64bit platform pc, all proj need to change to x.86 compile, Need exception catch on wpf loading because of xml parser error cause issue, appconfig need add in  useLegacyV2RuntimeActivationPolicy="true" on my pc. 
Really need solution pre-define build order because still unable to figure out how,
I  tried about a day but till now, no chance running all proj syn. 
Please put more documention mk. This really is impressive proj.
Far beyond my level though, cheers.!
Thanks.

**Comment by mkjeff** [comment]
There is no native platform library dependency, so, it is unnecessary to build with the specific platform.
'Any CPU' is suitable
