### ISSUE TITLE
SecsDevice based on NET461/NET472 cannot send SecsItem which contains large array

### ISSUE THREAD

**Issue by brucetju** [mkjeff/secs4net#64]
**Describe the bug**
NET461/NET472 cannot send SecsItem which contains large array while NET5.0/6.0 works ok

**To Reproduce**
1. use secsDevice project, and change "btnSendPrimary_Click" func,  original code is like this:[length of large array is 1136532, file size is about 1M, 200Kb file also tested, failed same.]
![image](https://user-images.githubusercontent.com/61259114/182066082-d8237742-0b07-4e92-8289-08ba32d321fe.png)

2. go to samples/SecsDevice/bin/Debug/net461;net472;net6.0-windows, open two same SecsDevice.exe window.
3. set up one as active, another as passive. wait for selected status. 
4. click "send" button, net6.0 works correctly, net461/net472 error is like this:
![image](https://user-images.githubusercontent.com/61259114/182067015-b34724eb-f952-424d-86c3-0d887879bed6.png)
![image](https://user-images.githubusercontent.com/61259114/182067058-924ebc67-14e8-4ee8-84c7-f3466783e537.png)

**Expected behavior**
net461/net472/net6.0 should act same for large array items.

**Screenshots**
as previous.

**Desktop (please complete the following information):**
 - OS: win10

Could you help me on this issue?

**Comment by mkjeff** [comment]
the issue was leading by incorrect usage on `ArrayPoolBufferWriter<T>` , fixed in 8b554854c7907c2fa12f663618eedfbaa973b3a5 

please upgrade to new version: 2.1.0
