### ISSUE TITLE
LinkTest timer not re-enable after reconnect

### ISSUE THREAD

**Issue by kkey0340** [mkjeff/secs4net#68]
The ```_timerLinkTest``` timer in the ```Disconnect()``` function will be disabled when ```CommunicationStateChanging(ConnectionState.Retry)``` is fired 

[timer get disable](https://github.com/mkjeff/secs4net/blob/c9deddffd66896acde13c6b10ec7fed2d80dc822/src/Secs4Net/HsmsConnection.cs#L230)

But the ```_timerLinkTest``` timer doesn't re-enable after reconnect

**Comment by mkjeff** [comment]
@kkey0340 thanks for ur report
