### ISSUE TITLE
I got Unhandled exception occurred on PipeDecoder producer

### ISSUE THREAD

**Issue by tondangerza** [mkjeff/secs4net#69]
Hi, I run my app (passive) on 13.00 PM and got Unhandled exception occurred on PipeDecoder producer on 08.00 PM
and then can't connect host (active) until re-initial host,
 I don't know what to do please can you help me?

*** logging ***
[05/09/2565 20:49:54 [Error] T3 Timeout[id=0x692EDA2E]: 45 sec.
[05/09/2565 20:49:09 [Error] Unhandled exception occurred on PipeDecoder producer
[05/09/2565 13:58:50 [MessageOut] REQUEST SPOOLED DATA ACKNOWLEDGE:'S6F24'
    <B [1] 0x02>
.

[05/09/2565 13:58:50 [MessageIn] 'S6F23'W
    <U1 [1] 0>
.

[05/09/2565 13:58:50 [MessageOut] CEEB:'S2F38'
    <B [1] 0x00>
.

![image](https://user-images.githubusercontent.com/51964193/188472557-b0fc0674-ac81-4d2f-b33d-1769dba34b5f.png)

Desktop 
OS: Windows 10 pro 64 bit

**Comment by mkjeff** [comment]
Please provide more detail about the unhandled exception, such as exception type and stack trace.

**Comment by tondangerza** [comment]
> Please provide more detail about the unhandled exception, such as exception type and stack trace.

After Linktest sending, I not yet found the unhandled exception, it's been 5-6 days I don't know why

**Comment by tossorrow** [comment]
> Please provide more detail about the unhandled exception, such as exception type and stack trace.

I may have reproduced the same exception.
![SECS-Retry](https://github.com/mkjeff/secs4net/assets/34665769/66d8f850-8558-45ef-9664-0be544b567fc)

windows 10 64 bit
.net framework4.6.1
winform
Secs4Net2.1.1

**Comment by mkjeff** [comment]
same as #94
