### ISSUE TITLE
too many T3

### ISSUE THREAD

**Issue by jiayueshe** [mkjeff/secs4net#73]
**Describe the bug**
WINFROM .NET 4.6.2 :  HSMS 100ms
too manny t3 timeout
日志记录:Received unexpected secondary message[0x1A4EE97B]. Maybe T3 timeout.
mayby is a bug

**To Reproduce**
WINFROM .NET 4.6.2 :  
HSMS 100ms
![image](https://user-images.githubusercontent.com/20673692/202878119-cba69d0e-374f-4be0-a538-ef90060b2591.png)

**Desktop (please complete the following information):**
 - OS: [windows]
 - CS: WINFROM  .NET 4.6.2

**Comment by wang9th** [comment]
你解决了吗？我也遇到了

**Comment by wang9th** [comment]
我将设备ID从127改到0就不再提示这个错误了，I changed the device ID from 127to 0 and stopped prompting this error.
