### ISSUE TITLE
Turn On the eqp one more time

### ISSUE THREAD

**Issue by eacanchen** [mkjeff/secs4net#74]
Hello Sir

When EQP is ON, the app is normal
![1](https://user-images.githubusercontent.com/49421594/204080433-bc4bd6ed-e902-41bd-9da2-8b54ba05ecd8.png)
at this time，I OFF the EQP，the app is normal too
![2](https://user-images.githubusercontent.com/49421594/204080434-603547e1-0780-4847-a4e1-6827571dd0c0.png)
but when I ON the EQP one more time，the app shows selected
![3](https://user-images.githubusercontent.com/49421594/204080438-9c361f1f-7a5e-4ed6-a993-b0c499867015.png)
for a while the app shows connecting
![4](https://user-images.githubusercontent.com/49421594/204080439-4a5074d4-aec3-4ad3-9320-b6667a03f86c.png)

sorry，my english is poor。

**Comment by kkey0340** [comment]
看看這的[Link](https://blog.csdn.net/jxb_memory/article/details/105442278#t22) "计时器"的部分
