### ISSUE TITLE
Linq方式添加item错误

### ISSUE THREAD

**Issue by KindergartenKiller2009** [mkjeff/secs4net#77]
按照示例里的Linq方式添加item是无法实现的,程序直接报错,

**Comment by blueyms** [comment]
> 按照示例里的Linq方式添加item是无法实现的,程序直接报错,

hello,你正在接入这个SECS吗？方便一起交流下吗，我这边也正在尝试接入

**Comment by blueyms** [comment]
any one can give me  heper? please contact me: robortly@163.com
