### ISSUE TITLE
Device reply S9Fx not catch SecsException

### ISSUE THREAD

**Issue by yestaro** [mkjeff/secs4net#8]
Hi, i try to test when my device reply S9F5
but An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll

The error was point to SecsGem.cs  line 466, method - SendDataMessageCompleteHandler(object socket, SocketAsyncEventArgs e)
```
if (_replyExpectedMsgs.ContainsKey(completeToken.Id))
            {
                **if (!completeToken.Task.Wait(T3))**
                {
                    _logger.Error($"T3 Timeout[id=0x{completeToken.Id:X8}]: {T3 / 1000} sec.");
                    completeToken.SetException(new SecsException(completeToken.MessageSent, Resources.T3Timeout));
                }
                _replyExpectedMsgs.TryRemove(completeToken.Id, out completeToken);
            }
```

**Comment by mkjeff** [comment]
Probably, the root cause is 'S9Fx' didn't contain matchable system id.
https://github.com/mkjeff/secs4net/blob/master/secs4net/Core/SecsCore/SecsGem.cs#L498

**Comment by yestaro** [comment]
Sorry, I should change the title of issue, it does catch SecsException, but also throws AggregateException.

After trace the code, it match the system id. and enter the method HandleReplyMessage(SecsMessage).
when device reply s9f5, the code run at
https://github.com/mkjeff/secs4net/blob/master/secs4net/Core/SecsCore/SecsGem.cs#L621

then SetException(new SecsException...)  called, the Task.Wait(T3) throws AggregateException
https://github.com/mkjeff/secs4net/blob/master/secs4net/Core/SecsCore/SecsGem.cs#L466

Because it is in another thread, my program can not handle AggregateException

**Comment by mkjeff** [comment]
Okay, I will fix it

**Comment by mkjeff** [comment]
fixed: https://github.com/mkjeff/secs4net/commit/56a5d33d0d872a82dec5950a85a141b569892430

**Comment by jinweihuang20** [comment]
兔
