### ISSUE TITLE
Can't response message after reconnect，自動重連之後不會回復消息了

### ISSUE THREAD

**Issue by wang9th** [mkjeff/secs4net#86]
我有一個攝像機，每當 Wafer Process End 後都會給我發送 S2F41 讓相機拍照，但是有時候 日志 會 記錄到 “Received Unrecognized Device Id Message” ，隨後自動重連，但是就不再回復 消息了，相機也不會拍照。
```
2023-09-17 02:31:11.3187 INFO <-- [0x000084D9] 'S2F41'W
    <L [2] 
        <A [5] 'START'>
        <L [2] 
            <L [2] 
                <A [10] 'photograph'>
                <A [3] 'PMA'>
            >
            <L [2] 
                <A [7] 'WaferID'>
                <A [10] 'A028060#22'>
            >
        >
    >
.


2023-09-17 02:31:11.3187 INFO PMA 收到 检测信号S2F41 携带 WaferID A028060#22
2023-09-17 02:31:11.3187 INFO --> [0x000084D9] 'S2F42'
    <L [2] 
        <B [1] 0x00>
        <L [2] 
            <A [16] 'PMA Taking Photo'>
            <B [1] 0x00>
        >
    >
.


2023-09-17 02:31:11.3187 INFO 发送 PMA 拍照信号S2F42
2023-09-17 02:31:11.3481 INFO <-- [0x000084DA] 'S2F41'W
    <L [0] 
    >
.


2023-09-17 02:31:11.3481 INFO <-- [0x0102410A] 'S18F84'
    <I4 [0] >
.


2023-09-17 02:31:11.4149 WARN Received Unrecognized Device Id Message

2023-09-17 02:31:11.4149 INFO --> [0x60571498] Unrecognized Device Id:'S9F1'
    <B [10] 0x54 0x41 0x12 0x54 0x00 0x02 0x01 0x02 0x41 0x0A>
.


2023-09-17 02:31:11.4149 INFO <-- [0x03504D42] 'S33F112'
    <L [2] 
        <A [7] 'WaferID'>
        <A [10] 'A028060#25'>
    >
.


2023-09-17 02:31:11.4149 WARN Received Unrecognized Device Id Message

2023-09-17 02:31:11.4149 INFO --> [0x60571499] Unrecognized Device Id:'S9F1'
    <B [10] 0x67 0x72 0x21 0x70 0x00 0x41 0x03 0x50 0x4D 0x42>
.


2023-09-17 02:31:15.7350 DEBUG  PMA test ===========================================2023_09_17 02-31-15.735
2023-09-17 02:31:15.9584 INFO --> [0x6057149A] 'S6F11'
    <L [3] 
        <U4 [1] 0>
        <U4 [1] 3000>
        <L [1] 
            <L [2] 
                <U4 [1] 2000>
                <L [2] 
                    <L [1] 
                        <L [2] 
                            <A [6] 'PMA OK'>
                            <A [9] 'non-Error'>
                        >
                    >
                    <A [10] 'A028060#22'>
                >
            >
        >
    >
.


2023-09-17 02:31:15.9584 INFO 发送 PMA 检测结果S6F11 绑定 WaferID A028060#22
2023-09-17 02:31:56.3691 INFO <-- [0x000084DB] 'S1F1'W
.


2023-09-17 02:32:41.3775 INFO <-- [0x000084EA] 'S1F1'W
.


2023-09-17 02:33:26.3884 INFO <-- [0x000084EC] 'S1F1'W
.


2023-09-17 02:34:16.3734 INFO <-- [0x000084EE] 'S1F1'W
.


2023-09-17 02:35:16.3770 INFO <-- [0x000084F0] 'S1F1'W
.


2023-09-17 02:36:16.3861 INFO <-- [0x000084F2] 'S1F1'W
.
```

**Comment by wang9th** [comment]
##### 利用 [issues 75](https://github.com/mkjeff/secs4net/issues/75) 的方法，解决了此问题。
将 ItemDecode.cs 中的
```csharp
public static unsafe Item DecodeFromFullBuffer(ref ReadOnlySequence<byte> bytes)
```
方法中的
```csharp
DecodeFormatAndLengthByteCount(bytes.FirstSpan.DangerousGetReferenceAt(0), out var format, out var lengthByteCount);
```
语句替换为
```csharp
var itemLenByte = bytes.Slice(0, 1).ToArray()[0];
//Trace.WriteLine(itemLenByte+"-<Different>-" + bytes.FirstSpan.DangerousGetReferenceAt(0));
DecodeFormatAndLengthByteCount(itemLenByte, out var format, out var lengthByteCount);
```

**Comment by wang9th** [comment]
### 在此记录一下问题复现步骤
1. 运行 Secs4net 中的 SecsDevice 项目，勾选 Passive，BufferSize 设置为 8192
2. 使用 FASTsim（version 2.70.0007） 作为服务端，连接客户端（SecsDevice ）
3. 使用 FASTsim 发送消息
```
'S2F41'W
    <L [2] 
        <A [5] 'START'>
        <L [2] 
            <L [2] 
                <A [10] 'photograph'>
                <A [3] 'PMA'>
            >
            <L [2] 
                <A [7] 'WaferID'>
                <A [10] 'A028060#22'>
            >
        >
    >
.
```
4. SecsDevice 日志会记录到错误，这个错误一半不会马上出现，要多次消息交互之后才会出现，如果复现不出来，则可以尝试调整 BufferSize 为 5120 或者 65535 亦或其他值
```
<-- [0x00000013] 'S2F41'W
    <L [0] 
    >
.

<-- [0x0102410A] 'S18F84'
    <I4 [0] >
.

Received Unrecognized Device Id Message
--> [0x2025967B] Unrecognized Device Id:'S9F1'
    <B [10] 0x54 0x41 0x12 0x54 0x00 0x02 0x01 0x02 0x41 0x0A>
.

<-- [0x03504D41] 'S33F112'
    <L [2] 
        <A [7] 'WaferID'>
        <A [10] 'A028060#22'>
    >
.

Received Unrecognized Device Id Message
--> [0x2025967C] Unrecognized Device Id:'S9F1'
    <B [10] 0x67 0x72 0x21 0x70 0x00 0x41 0x03 0x50 0x4D 0x41>
.

Unexpected exception on StartAsyncStreamDecoderAsync

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at System.ThrowHelper.ThrowStartOrEndArgumentValidationException(Int64 start)
   at System.Buffers.ReadOnlySequence`1.Slice(Int64 start, Int64 length)
   at System.Buffers.ReadOnlySequence`1.Slice(Int32 start, Int32 length)
   at Secs4Net.Item.DecodeFromFullBuffer(ReadOnlySequence`1& bytes) in C:\Users\Heath\Desktop\secs4net\src\Secs4Net\Item.Decode.cs:line 59
   at Secs4Net.PipeDecoder.DecodeLoopAsync(ChannelWriter`1 controlMessageWriter, ChannelWriter`1 dataMessageWriter, PipeReader reader, CancellationToken cancellation) in C:\Users\Heath\Desktop\secs4net\src\Secs4Net\PipeDecoder.cs:line 102
   at Secs4Net.HsmsConnection.StartPipeDecoderConsumerAsync(CancellationToken cancellation) in C:\Users\Heath\Desktop\secs4net\src\Secs4Net\HsmsConnection.cs:line 316
```

**Comment by jackliu0088** [comment]
感谢，我也发现了这个问题，但是不知道在哪里更改，谢谢

**Comment by wang9th** [comment]
> 感谢，我也发现了这个问题，但是不知道在哪里更改，谢谢

我提了 [pull 87](https://github.com/mkjeff/secs4net/pull/87)，可以查看这个的更改，然后你对应修改就好了

**Comment by mkjeff** [comment]
I made a mistake here that assumed the first span(segment) of `ReadOnlySequence<byte>` must not be empty, but the truth is `ReadOnlySequence<T>` could contain empty segments. Refer the documentation [here](https://learn.microsoft.com/en-us/dotnet/standard/io/buffers#empty-segments).
 
It is also reproducible by unit tests, just prepending on an empty segment before normal encoded bytes.

I will try to fix it, but no timeline guarantees.

btw. potentially the same problem might be [here](https://github.com/mkjeff/secs4net/blob/base/src/Secs4Net/PipeDecoder.cs#L116-L120)

**Comment by wang9th** [comment]
> I made a mistake here that assumed the first span(segment) of `ReadOnlySequence<byte>` must not be empty, but the truth is `ReadOnlySequence<T>` could contain empty segments. Refer the documentation [here](https://learn.microsoft.com/en-us/dotnet/standard/io/buffers#empty-segments).
> 
> It is also reproducible by unit tests, just prepending on an empty segment before normal encoded bytes.
> 
> I will try to fix it, but no timeline guarantees.
> 
> btw. potentially the same problem might be [here](https://github.com/mkjeff/secs4net/blob/base/src/Secs4Net/PipeDecoder.cs#L116-L120)

I am Looking forward to your update，你是台灣人嗎？

**Comment by wang9th** [comment]
> I made a mistake here that assumed the first span(segment) of `ReadOnlySequence<byte>` must not be empty, but the truth is `ReadOnlySequence<T>` could contain empty segments. Refer the documentation [here](https://learn.microsoft.com/en-us/dotnet/standard/io/buffers#empty-segments).
> 
> It is also reproducible by unit tests, just prepending on an empty segment before normal encoded bytes.
> 
> I will try to fix it, but no timeline guarantees.
> 
> btw. potentially the same problem might be [here](https://github.com/mkjeff/secs4net/blob/base/src/Secs4Net/PipeDecoder.cs#L116-L120)

你知道如何將項目引用的dll都放在一個文件夾中管理嗎？我的項目有一個dll文件夾，項目引用的dll都放在裏面，但是生成的debug目錄仍是在根目錄，我如何讓生成後的dll也都在dll文件夾中？

**Comment by mkjeff** [comment]
checkout the branch [bug-readonlysequence-has-empty-segment](https://github.com/mkjeff/secs4net/tree/bug-readonlysequence-has-empty-segment)

also added the unit test to address the issue.

**Comment by wang9th** [comment]
> checkout the branch [bug-readonlysequence-has-empty-segment](https://github.com/mkjeff/secs4net/tree/bug-readonlysequence-has-empty-segment)
> 
> also added the unit test to address the issue.

Does nuget package have synchronized updates?

**Comment by mkjeff** [comment]
You can verify from the source code(project reference) first. secs4net package will be updated later.
