### ISSUE TITLE
How can I use Secs4Net to create a passive host EAP to connect to many equipments?

### ISSUE THREAD

**Issue by xunan27** [mkjeff/secs4net#93]
I want to create a passive host to connect to about 20 active equipments,so I need to create 20 HsmsConnections.As I use passive mode,in each HsmsConnection,the port 5000 will be listened,so it will occur an error that "one port can be used just once",so how can I use Secs4Net to create a passive host EAP to connect to many equipments?

**Comment by mkjeff** [comment]
it is the `HSMS-SS` implementation, didn't cover your scenario

**Comment by mkjeff** [comment]
it is the HSMS-SS implementation, didn't cover your scenario

**Comment by chenlongkuan** [comment]
Is this supported? Can give any demo code?  Thanks.
