### ISSUE TITLE
EQ cannot be connected after reopen host severial times while selected

### ISSUE THREAD

**Issue by brucetju** [mkjeff/secs4net#94]
**Describe the bug**
EQ cannot be connected after reopen host severial times while selected. Not every time, sometimes happens.

**To Reproduce**
1. open two secsDevice(net461 also showed in following picture), one is set as eq while another is set as host.
2. enable eq
3. enable host, two side will be both in selected mode after a while
4. close host app(not Disable host). Normally eq side will be set in Connecting status as following:
![图片](https://github.com/mkjeff/secs4net/assets/61259114/a619cbfc-a16c-4d5b-9a91-440094a32bf4)

but sometimes eq side will stay in Retry status showing exception message "Unhandled exception occurred on PipeDecoder producer, 指定的参数已超出有效值的范围" as following:
![图片](https://github.com/mkjeff/secs4net/assets/61259114/64f7e4ee-6cbb-4743-ad8e-56cc76dedaf7)

Once switched into Retry status, even disable and enable eq again, host cann't connect to eq side. and when click on disable button, error message pop out as following:
![图片](https://github.com/mkjeff/secs4net/assets/61259114/6744d9a8-9258-463a-b08b-ac26db20d4de)

**Expected behavior**
Except eq side can be connected in all condition at any time.

**Desktop (please complete the following information):**
 - OS: Win10 x64
 - Secs4net Version is ffe91b
![图片](https://github.com/mkjeff/secs4net/assets/61259114/48ab978c-33da-45e4-94df-4b490a937636)

**Comment by mkjeff** [comment]
I can't reproduce on `net472` while using the same code base version. 

I'm curious why your TFM is `net461`.
`SecsDevice` project can't be built if TFM changes to `net461`.

maybe you can take a look at [this](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0#select-net-standard-version).

**Comment by brucetju** [comment]
Yeah... sorry for my mistake, net461 is built previously.  Currently, secs4net v2.3.2.0 with LinkTestInterval enabled solved my connection failure issue!
Thank you very much!
